
SELECT ENAME, SAL, COMM, SAL*12+COMM,
NVL(COMM,0), SAL*12+NVL(COMM,0)
FROM EMP
ORDER BY JOB;

SELECT EMPNO, ENAME,NVL(TO_CHAR(MGR,'9999'),'CEO') "MANAGER"
FROM EMP
WHERE MGR IS NULL;

SELECT EMPNO,ENAME,SAL,COMM,NVL2(COMM,SAL*12+COMM,SAL*12) ANNSAL
FROM EMP
WHERE MGR IS NOT NULL;

SELECT ENAME,DEPTNO,
DECODE(DEPTNO, 10, 'ACCOUNTING',
                             20, 'RESEARCH',
                             30, 'SALES',
                             40, 'OPERATIONS') "DNAME"
                             FROM EMP;
-- AS FROM EMP; 로도 사용 가능

SELECT ENAME, JOB, SAL,
DECODE(JOB, 'ANALYST', SAL*1.05,
                      'SALESMAN', SAL*1.1,
                      'MANAGER', SAL*1.15,
                      'CLERK', SAL*1.1) "UpSal"    
                     FROM EMP;
                     
SELECT ENAME,DEPTNO,
             CASE WHEN DEPTNO = 10 THEN 'ACCOUNTING'
                       WHEN DEPTNO = 20 THEN 'RESEARCH'
                       WHEN DEPTNO = 30 THEN 'SALES'
                       WHEN DEPTNO = 40 THEN 'OPERATIONS'
            END AS DNAME
FROM EMP;
--1번
SELECT SUBSTR(HIREDATE,1,2) 년도, SUBSTR (HIREDATE,4,2) 달
FROM EMP;
--2번
SELECT*
FROM EMP
WHERE SUBSTR(HIREDATE,4,2)= '04';
--3번
SELECT *
FROM EMP
WHERE MOD(EMPNO,2) = 0;
--4번
SELECT HIREDATE, TO_CHAR(HIREDATE, 'YY/MON/DD DY')
FROM EMP;
--5번
SELECT TRUNC(SYSDATE-TO_DATE('2024/01/01','YYYY/MM/DD')) DAYS
FROM DUAL;
--6번
SELECT * FROM EMP;

SELECT EMPNO,ENAME,JOB,MGR,NVL(MGR,0)
FROM EMP;

SELECT EMPNO,ENAME,JOB,MGR,NVL2(MGR,MGR,0)
FROM EMP;
--7번

SELECT EMPNO, ENAME, JOB, SAL,
DECODE(JOB,'ANALYST', SAL+200, 'SALESMAN',SAL+180, 'MANAGER',SAL+150,'CLERK',SAL+100)
FROM EMP;

SELECT JOB, SAL,
DECODE(JOB,'ANALYST', SAL+200, 'SALESMAN',SAL+180, 'MANAGER',SAL+150,'CLERK',SAL+100)
FROM EMP;

-- DECODE 사용할때 전에 ,가 있어야함.